### ISSUE TITLE
this data can’t be found

### ISSUE THREAD

**Issue by liamxg** [genomicsurveillance/YFV-surveillance#2]
<img width="1235" alt="image" src="https://github.com/genomicsurveillance/YFV-surveillance/assets/46078579/2a9f9c77-eec5-4f08-8ec5-13a3a256dcd2">

**Comment by liamxg** [comment]
@genomicsurveillance

**Comment by genomicsurveillance** [comment]
fixed

**Comment by liamxg** [comment]
thanks.
