### ISSUE TITLE
how to deal with this?

### ISSUE THREAD

**Issue by liamxg** [genomicsurveillance/YFV-surveillance#3]
<img width="875" alt="image" src="https://github.com/genomicsurveillance/YFV-surveillance/assets/46078579/42cfc32a-597a-409b-be7c-1769a60c6e1a">

**Comment by genomicsurveillance** [comment]
This error is due to the dataset that the link was broken. I believe you can run the script with the dataset.

**Comment by liamxg** [comment]
I tried other datasets, still have same error. Try again?

**Comment by genomicsurveillance** [comment]
You need to create two directories "yfv2" and "yfv3" inside data. Did you make it?

**Comment by liamxg** [comment]
<img width="654" alt="image" src="https://github.com/genomicsurveillance/YFV-surveillance/assets/46078579/c3c33670-e1af-45ad-883a-d5e34015e702">
passed, thanks.
