### ISSUE TITLE
Could you please help me figure out why my plot is different to yours, thanks.

### ISSUE THREAD

**Issue by liamxg** [genomicsurveillance/YFV-surveillance#5]
<img width="734" alt="image" src="https://github.com/genomicsurveillance/YFV-surveillance/assets/46078579/3ff0b4c2-3eb2-4d1a-871f-662d6b8a25f7">

**Comment by genomicsurveillance** [comment]
All our figures then go through an image editor. As we create panels, the colours of the figures need to be in harmony.
